Begin adding missing repositories

diff --git a/server/script/generate b/server/script/generate
--- a/server/script/generate
+++ b/server/script/generate
@@ -58,16 +58,55 @@ function generate_service {
 
 function generate_repo {
 
-    REPO=$1
+    SERVICE_CC=$1
+    if [ -z "$SERVICE_CC" ]; then
+        echo "Missing service name, cannot create new service"
+        usage
+        exit 1
+    fi
 
-    if [ -z "$REPO" ]; then
+    # check service camel case
+    case ${SERVICE_CC:0:1} in
+    [A-Z])
+        echo "$SERVICE_CC looks good..."
+        ;;
+    *)
+        echo "$SERVICE_CC must be in CamelCase thanks!"
+        exit
+        ;;
+    esac
+
+    # lower/upper case service name
+    SERVICE_LC=$(echo "$SERVICE_CC" | tr '[:upper:]' '[:lower:]')
+    SERVICE_UC=$(echo "$SERVICE_CC" | tr '[:lower:]' '[:upper:]')
+
+    REPO_CC=$2
+    if [ -z "$REPO_CC" ]; then
         echo "Missing repo name, cannot create new repo"
         usage
         exit 1
     fi
 
-    echo "Generating repo ${REPO}"
+    # check service camel case
+    case ${REPO_CC:0:1} in
+    [A-Z])
+        echo "$REPO_CC looks good..."
+        ;;
+    *)
+        echo "$REPO_CC must be in CamelCase thanks!"
+        exit
+        ;;
+    esac
 
+    # lower/upper case repository name
+    # shellcheck disable=SC2034
+    REPO_LC=$(echo "$REPO_CC" | tr '[:upper:]' '[:lower:]')
+    # shellcheck disable=SC2034
+    REPO_UC=$(echo "$REPO_CC" | tr '[:lower:]' '[:upper:]')
+
+    echo "Generating repo ${REPO_CC} in service ${SERVICE_CC}"
+
+    # TODO: Actually generate a repository from the template service eh?
 }
 
 # command (repo, service)
