Rectify shellcheck errors

diff --git a/server/script/retry b/server/script/retry
--- a/server/script/retry
+++ b/server/script/retry
@@ -8,19 +8,29 @@ function retry_cmd {
   local delay=5
   local delay_inc=5
 
-  echo "=> Command $@"
+  echo "=> Command $*"
 
   while true; do
-    "$@" && break || {
-      if [[ $n -lt $max ]]; then
-        ((n++))
-        echo "=> Command failed. Trying again in $delay seconds. Attempt $n/$max:"
-        sleep $delay;
-        delay=$[$delay+$delay_inc]
-      else
-        echo "=> Command failed after $n attempts, exiting.." >&2
-        exit 1
-      fi
-    }
+    # "$@" && break || {
+    #   if [[ $n -lt $max ]]; then
+    #     ((n++))
+    #     echo "=> Command failed. Trying again in $delay seconds. Attempt $n/$max:"
+    #     sleep $delay;
+    #     delay=$[$delay+$delay_inc]
+    #   else
+    #     echo "=> Command failed after $n attempts, exiting.." >&2
+    #     exit 1
+    #   fi
+    # }
+    "$@" && break
+    if [[ $n -lt $max ]]; then
+      ((n++))
+      echo "=> Command failed. Trying again in $delay seconds. Attempt $n/$max:"
+      sleep $delay;
+      delay=$($delay+$delay_inc)
+    else
+      echo "=> Command failed after $n attempts, exiting.." >&2
+      exit 1
+    fi
   done
 }
